# Generated by Django 3.1.5 on 2021-01-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(),
        ),
    ]
