# Generated by Django 3.1.5 on 2021-01-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapi', '0002_auto_20210118_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
