# Generated by Django 3.1.5 on 2021-01-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapi', '0003_auto_20210119_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
