# Generated by Django 3.1.5 on 2021-01-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapi', '0004_auto_20210119_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
