# Generated by Django 3.1.5 on 2021-01-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketapi', '0005_auto_20210119_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_remise', models.IntegerField()),
                ('promotion_free', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapi.promotion'),
        ),
    ]
