# Generated by Django 3.1.5 on 2021-01-20 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketapi', '0006_auto_20210120_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
