# Generated by Django 3.1.5 on 2021-01-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapi', '0007_promotion_promotion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotion_free',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_remise',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
